first commit --kaminari
RyoMachida71/fjord-books_app pull request #2
Opened 2021-11-30 02:33 UTC by machida-being

提出物になります。
レビューをお願いいたします。

2021-12-05 13:55 UTC, u1tnk requested changes

2021-12-05 13:55 UTC, u1tnk commented on app/controllers/books_controller.rb
> +    @books = @books.page(params[:page]).per(5)
この行を追加したら上の `Book.all`は不要なので削除しましょう。

2021-12-06 04:38 UTC, machida-being commented on app/controllers/books_controller.rb
> +    @books = @books.page(params[:page]).per(5)
削除しました。
完全に不要なコードでした。
次から気を付けます。

2021-12-06 09:41 UTC, u1tnk approved these changes

2021-12-14 05:16 UTC, merged